Not Found: /favicon.ico
Not Found: /eegdata/excerpt1_50/-60/20/
Not Found: /eegdata/excerpt1_50/-60/20/
Not Found: /eegdata/excerpt1_50/-60/20/
Not Found: /eegdata/excerpt1_50/-100/20/
Not Found: /eegdata/excerpt1_50/-100/20/
Not Found: /eegdata/excerpt1_50/-20/20/
Not Found: /eegdata/excerpt1_50/-20/20/
Not Found: /eegdata/excerpt1_50/-60/20/
Not Found: /eegdata/excerpt1_50/-60/20/
Not Found: /eegdata/excerpt1_50/-20/20/
Not Found: /favicon.ico
Internal Server Error: /viewer/getannotations
Traceback (most recent call last):
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/vagrant/crowdspot/crowdspot/viewer/views.py", line 175, in getAnnotations
    annotator = Annotator.objects.get(username=username)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: Annotator matching query does not exist.
Internal Server Error: /viewer/getannotations
Traceback (most recent call last):
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/vagrant/crowdspot/crowdspot/viewer/views.py", line 175, in getAnnotations
    annotator = Annotator.objects.get(username=username)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: Annotator matching query does not exist.
Internal Server Error: /viewer/getannotations
Traceback (most recent call last):
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/vagrant/crowdspot/crowdspot/viewer/views.py", line 175, in getAnnotations
    annotator = Annotator.objects.get(username=username)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: Annotator matching query does not exist.
Internal Server Error: /viewer/getannotations
Traceback (most recent call last):
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/vagrant/crowdspot/crowdspot/viewer/views.py", line 175, in getAnnotations
    annotator = Annotator.objects.get(username=username)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: Annotator matching query does not exist.
Internal Server Error: /viewer/getannotations
Traceback (most recent call last):
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/vagrant/crowdspot/crowdspot/viewer/views.py", line 175, in getAnnotations
    annotator = Annotator.objects.get(username=username)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: Annotator matching query does not exist.
Internal Server Error: /viewer/getannotations
Traceback (most recent call last):
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/vagrant/crowdspot/crowdspot/viewer/views.py", line 175, in getAnnotations
    annotator = Annotator.objects.get(username=username)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: Annotator matching query does not exist.
Internal Server Error: /viewer/getannotations
Traceback (most recent call last):
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/vagrant/crowdspot/crowdspot/viewer/views.py", line 175, in getAnnotations
    annotator = Annotator.objects.get(username=username)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: Annotator matching query does not exist.
Internal Server Error: /viewer/getannotations
Traceback (most recent call last):
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/vagrant/crowdspot/crowdspot/viewer/views.py", line 175, in getAnnotations
    annotator = Annotator.objects.get(username=username)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: Annotator matching query does not exist.
Internal Server Error: /viewer/getannotations
Traceback (most recent call last):
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/vagrant/crowdspot/crowdspot/viewer/views.py", line 175, in getAnnotations
    annotator = Annotator.objects.get(username=username)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: Annotator matching query does not exist.
Internal Server Error: /viewer/getannotations
Traceback (most recent call last):
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/vagrant/crowdspot/crowdspot/viewer/views.py", line 175, in getAnnotations
    annotator = Annotator.objects.get(username=username)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: Annotator matching query does not exist.
Internal Server Error: /viewer/getannotations
Traceback (most recent call last):
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/vagrant/crowdspot/crowdspot/viewer/views.py", line 175, in getAnnotations
    annotator = Annotator.objects.get(username=username)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: Annotator matching query does not exist.
Internal Server Error: /viewer/getannotations
Traceback (most recent call last):
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/vagrant/crowdspot/crowdspot/viewer/views.py", line 175, in getAnnotations
    annotator = Annotator.objects.get(username=username)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: Annotator matching query does not exist.
Internal Server Error: /viewer/getannotations
Traceback (most recent call last):
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/vagrant/crowdspot/crowdspot/viewer/views.py", line 175, in getAnnotations
    annotator = Annotator.objects.get(username=username)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: Annotator matching query does not exist.
Internal Server Error: /viewer/getannotations
Traceback (most recent call last):
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/vagrant/crowdspot/crowdspot/viewer/views.py", line 175, in getAnnotations
    annotator = Annotator.objects.get(username=username)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: Annotator matching query does not exist.
Forbidden (CSRF token missing or incorrect.): /viewer/addfeature
Forbidden (CSRF token missing or incorrect.): /viewer/addfeature
Internal Server Error: /viewer/getannotations
Traceback (most recent call last):
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/vagrant/crowdspot/crowdspot/viewer/views.py", line 175, in getAnnotations
    annotator = Annotator.objects.get(username=username)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: Annotator matching query does not exist.
Internal Server Error: /viewer/getannotations
Traceback (most recent call last):
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/vagrant/crowdspot/crowdspot/viewer/views.py", line 175, in getAnnotations
    annotator = Annotator.objects.get(username=username)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: Annotator matching query does not exist.
Internal Server Error: /viewer/getannotations
Traceback (most recent call last):
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/vagrant/crowdspot/crowdspot/viewer/views.py", line 175, in getAnnotations
    annotator = Annotator.objects.get(username=username)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: Annotator matching query does not exist.
Internal Server Error: /viewer/getannotations
Traceback (most recent call last):
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/vagrant/crowdspot/crowdspot/viewer/views.py", line 175, in getAnnotations
    annotator = Annotator.objects.get(username=username)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: Annotator matching query does not exist.
Internal Server Error: /viewer/getannotations
Traceback (most recent call last):
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/vagrant/crowdspot/crowdspot/viewer/views.py", line 175, in getAnnotations
    annotator = Annotator.objects.get(username=username)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: Annotator matching query does not exist.
Internal Server Error: /viewer/getannotations
Traceback (most recent call last):
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/vagrant/crowdspot/crowdspot/viewer/views.py", line 175, in getAnnotations
    annotator = Annotator.objects.get(username=username)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: Annotator matching query does not exist.
Internal Server Error: /viewer/getannotations
Traceback (most recent call last):
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/vagrant/crowdspot/crowdspot/viewer/views.py", line 175, in getAnnotations
    annotator = Annotator.objects.get(username=username)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: Annotator matching query does not exist.
Internal Server Error: /viewer/getannotations
Traceback (most recent call last):
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/vagrant/crowdspot/crowdspot/viewer/views.py", line 175, in getAnnotations
    annotator = Annotator.objects.get(username=username)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: Annotator matching query does not exist.
Internal Server Error: /viewer/getannotations
Traceback (most recent call last):
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/vagrant/crowdspot/crowdspot/viewer/views.py", line 175, in getAnnotations
    annotator = Annotator.objects.get(username=username)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: Annotator matching query does not exist.
Internal Server Error: /viewer/getannotations
Traceback (most recent call last):
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/vagrant/crowdspot/crowdspot/viewer/views.py", line 175, in getAnnotations
    annotator = Annotator.objects.get(username=username)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: Annotator matching query does not exist.
Internal Server Error: /viewer/getannotations
Traceback (most recent call last):
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/vagrant/crowdspot/crowdspot/viewer/views.py", line 175, in getAnnotations
    annotator = Annotator.objects.get(username=username)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: Annotator matching query does not exist.
Internal Server Error: /viewer/getannotations
Traceback (most recent call last):
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/vagrant/crowdspot/crowdspot/viewer/views.py", line 175, in getAnnotations
    annotator = Annotator.objects.get(username=username)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: Annotator matching query does not exist.
Internal Server Error: /viewer/getannotations
Traceback (most recent call last):
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/vagrant/crowdspot/crowdspot/viewer/views.py", line 175, in getAnnotations
    annotator = Annotator.objects.get(username=username)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: Annotator matching query does not exist.
Internal Server Error: /viewer/getannotations
Traceback (most recent call last):
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/vagrant/crowdspot/crowdspot/viewer/views.py", line 175, in getAnnotations
    annotator = Annotator.objects.get(username=username)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: Annotator matching query does not exist.
Internal Server Error: /viewer/getannotations
Traceback (most recent call last):
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/vagrant/crowdspot/crowdspot/viewer/views.py", line 175, in getAnnotations
    annotator = Annotator.objects.get(username=username)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: Annotator matching query does not exist.
Internal Server Error: /viewer/getannotations
Traceback (most recent call last):
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/vagrant/crowdspot/crowdspot/viewer/views.py", line 175, in getAnnotations
    annotator = Annotator.objects.get(username=username)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: Annotator matching query does not exist.
Internal Server Error: /viewer/getannotations
Traceback (most recent call last):
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/vagrant/crowdspot/crowdspot/viewer/views.py", line 175, in getAnnotations
    annotator = Annotator.objects.get(username=username)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: Annotator matching query does not exist.
Internal Server Error: /viewer/getannotations
Traceback (most recent call last):
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/vagrant/crowdspot/crowdspot/viewer/views.py", line 175, in getAnnotations
    annotator = Annotator.objects.get(username=username)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: Annotator matching query does not exist.
Internal Server Error: /viewer/getannotations
Traceback (most recent call last):
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/vagrant/crowdspot/crowdspot/viewer/views.py", line 175, in getAnnotations
    annotator = Annotator.objects.get(username=username)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: Annotator matching query does not exist.
Forbidden (CSRF token missing or incorrect.): /viewer/addfeature
Not Found: /eegdata/excerpt1_50/-100/20/
Not Found: /eegdata/excerpt1_50/-100/20/
Not Found: /eegdata/excerpt1_50/-100/20/
Not Found: /eegdata/excerpt1_50/-100/20/
Not Found: /eegdata/excerpt1_50/-100/20/
Not Found: /eegdata/excerpt1_50/-100/20/
