Internal Server Error: /viewer/addfeature
Traceback (most recent call last):
  File "/Users/joshbradshaw/anaconda/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/joshbradshaw/anaconda/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/joshbradshaw/Documents/crowdEEG/crowdspot/crowdspot/viewer/views.py", line 105, in saveFeature
    return HttpResponseBadRequest("This view accepts POST requests only")
NameError: global name 'HttpResponseBadRequest' is not defined
Internal Server Error: /viewer/deletefeature
Traceback (most recent call last):
  File "/Users/joshbradshaw/anaconda/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/joshbradshaw/anaconda/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/joshbradshaw/Documents/crowdEEG/crowdspot/crowdspot/viewer/views.py", line 125, in deleteFeature
    start=time_start,end=time_end,channel=channel,annotator=annotator,recording=recording)
  File "/Users/joshbradshaw/anaconda/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/joshbradshaw/anaconda/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: Feature matching query does not exist.
Internal Server Error: /viewer/addfeature
Traceback (most recent call last):
  File "/Users/joshbradshaw/anaconda/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/joshbradshaw/anaconda/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/joshbradshaw/Documents/crowdEEG/crowdspot/crowdspot/viewer/views.py", line 84, in saveFeature
    return HttpResponseBadRequest("Cannot save features while the answer is displayed")
NameError: global name 'HttpResponseBadRequest' is not defined
Internal Server Error: /viewer/deletefeature
Traceback (most recent call last):
  File "/Users/joshbradshaw/anaconda/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/joshbradshaw/anaconda/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/joshbradshaw/Documents/crowdEEG/crowdspot/crowdspot/viewer/views.py", line 128, in deleteFeature
    start=time_start,end=time_end,channel=channel,annotator=annotator,recording=recording)
  File "/Users/joshbradshaw/anaconda/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/joshbradshaw/anaconda/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: Feature matching query does not exist.
Internal Server Error: /viewer/deletefeature
Traceback (most recent call last):
  File "/Users/joshbradshaw/anaconda/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/joshbradshaw/anaconda/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/joshbradshaw/Documents/crowdEEG/crowdspot/crowdspot/viewer/views.py", line 128, in deleteFeature
    start=time_start,end=time_end,channel=channel,annotator=annotator,recording=recording)
  File "/Users/joshbradshaw/anaconda/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/joshbradshaw/anaconda/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: Feature matching query does not exist.
Internal Server Error: /viewer/deletefeature
Traceback (most recent call last):
  File "/Users/joshbradshaw/anaconda/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/joshbradshaw/anaconda/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/joshbradshaw/Documents/crowdEEG/crowdspot/crowdspot/viewer/views.py", line 128, in deleteFeature
    start=time_start,end=time_end,channel=channel,annotator=annotator,recording=recording)
  File "/Users/joshbradshaw/anaconda/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/joshbradshaw/anaconda/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: Feature matching query does not exist.
Internal Server Error: /viewer/deletefeature
Traceback (most recent call last):
  File "/Users/joshbradshaw/anaconda/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/joshbradshaw/anaconda/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/joshbradshaw/Documents/crowdEEG/crowdspot/crowdspot/viewer/views.py", line 128, in deleteFeature
    start=time_start,end=time_end,channel=channel,annotator=annotator,recording=recording)
  File "/Users/joshbradshaw/anaconda/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/joshbradshaw/anaconda/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: Feature matching query does not exist.
Internal Server Error: /viewer/deletefeature
Traceback (most recent call last):
  File "/Users/joshbradshaw/anaconda/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/joshbradshaw/anaconda/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/joshbradshaw/Documents/crowdEEG/crowdspot/crowdspot/viewer/views.py", line 128, in deleteFeature
    start=time_start,end=time_end,channel=channel,annotator=annotator,recording=recording)
  File "/Users/joshbradshaw/anaconda/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/joshbradshaw/anaconda/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: Feature matching query does not exist.
Internal Server Error: /viewer/deletefeature
Traceback (most recent call last):
  File "/Users/joshbradshaw/anaconda/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/joshbradshaw/anaconda/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/joshbradshaw/Documents/crowdEEG/crowdspot/crowdspot/viewer/views.py", line 129, in deleteFeature
    start=time_start,end=time_end,channel=channel,annotator=annotator,recording=recording)
  File "/Users/joshbradshaw/anaconda/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/joshbradshaw/anaconda/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: Feature matching query does not exist.
Internal Server Error: /viewer/deletefeature
Traceback (most recent call last):
  File "/Users/joshbradshaw/anaconda/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/joshbradshaw/anaconda/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/joshbradshaw/Documents/crowdEEG/crowdspot/crowdspot/viewer/views.py", line 129, in deleteFeature
    start=time_start,end=time_end,channel=channel,annotator=annotator,recording=recording)
  File "/Users/joshbradshaw/anaconda/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/joshbradshaw/anaconda/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: Feature matching query does not exist.
Internal Server Error: /viewer/deletefeature
Traceback (most recent call last):
  File "/Users/joshbradshaw/anaconda/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/joshbradshaw/anaconda/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/joshbradshaw/Documents/crowdEEG/crowdspot/crowdspot/viewer/views.py", line 128, in deleteFeature
    start=time_start,end=time_end,channel=channel,annotator=annotator,recording=recording)
  File "/Users/joshbradshaw/anaconda/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/joshbradshaw/anaconda/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: Feature matching query does not exist.
Internal Server Error: /viewer/deletefeature
Traceback (most recent call last):
  File "/Users/joshbradshaw/anaconda/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/joshbradshaw/anaconda/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/joshbradshaw/Documents/crowdEEG/crowdspot/crowdspot/viewer/views.py", line 128, in deleteFeature
    start=time_start,end=time_end,channel=channel,annotator=annotator,recording=recording)
  File "/Users/joshbradshaw/anaconda/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/joshbradshaw/anaconda/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: Feature matching query does not exist.
Internal Server Error: /viewer/deletefeature
Traceback (most recent call last):
  File "/Users/joshbradshaw/anaconda/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/joshbradshaw/anaconda/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/joshbradshaw/Documents/crowdEEG/crowdspot/crowdspot/viewer/views.py", line 128, in deleteFeature
    start=time_start,end=time_end,channel=channel,annotator=annotator,recording=recording)
  File "/Users/joshbradshaw/anaconda/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/joshbradshaw/anaconda/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: Feature matching query does not exist.
Internal Server Error: /viewer/
Traceback (most recent call last):
  File "/Users/joshbradshaw/anaconda/lib/python2.7/site-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/joshbradshaw/anaconda/lib/python2.7/site-packages/django/core/urlresolvers.py", line 368, in resolve
    sub_match = pattern.resolve(new_path)
  File "/Users/joshbradshaw/anaconda/lib/python2.7/site-packages/django/core/urlresolvers.py", line 240, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/Users/joshbradshaw/anaconda/lib/python2.7/site-packages/django/core/urlresolvers.py", line 247, in callback
    self._callback = get_callable(self._callback_str)
  File "/Users/joshbradshaw/anaconda/lib/python2.7/site-packages/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/Users/joshbradshaw/anaconda/lib/python2.7/site-packages/django/core/urlresolvers.py", line 106, in get_callable
    mod = import_module(mod_name)
  File "/Users/joshbradshaw/anaconda/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/joshbradshaw/Documents/crowdEEG/crowdspot/crowdspot/viewer/views.py", line 140
    use_expert_annotations = True if request.GET.get('use_expert_annotations', False) == 'true'
                                                                                              ^
SyntaxError: invalid syntax
Internal Server Error: /viewer/deletefeature
Traceback (most recent call last):
  File "/Users/joshbradshaw/anaconda/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/joshbradshaw/anaconda/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/joshbradshaw/Documents/crowdEEG/crowdspot/crowdspot/viewer/views.py", line 128, in deleteFeature
    start=time_start,end=time_end,channel=channel,annotator=annotator,recording=recording)
  File "/Users/joshbradshaw/anaconda/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/joshbradshaw/anaconda/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: Feature matching query does not exist.
Internal Server Error: /viewer/addfeature
Traceback (most recent call last):
  File "/Users/joshbradshaw/anaconda/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view crowdspot.viewer.views.saveFeature didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /viewer/deletefeature
Traceback (most recent call last):
  File "/Users/joshbradshaw/anaconda/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/joshbradshaw/anaconda/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/joshbradshaw/Documents/crowdEEG/crowdspot/crowdspot/viewer/views.py", line 128, in deleteFeature
    start=time_start,end=time_end,channel=channel,annotator=annotator,recording=recording)
  File "/Users/joshbradshaw/anaconda/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/joshbradshaw/anaconda/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: Feature matching query does not exist.
Not Found: /eegdata/excerpt1_50/-20/20/
Not Found: /expert/
Not Found: /viewr
